[package]
name = "permutate-macro"
version = "0.4.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.51"
syn = { version = "2.0.4", features = ["full", "visit-mut"] }
quote = "1.0.23"
json = "0.12.4"
